### ISSUE TITLE
Add Mint Count to Minimix Metrics

### ISSUE THREAD

**Issue by lootmatic** [wavpoint/wavpoint-monorepo#9]
Can we add a mint count to the left of play count on the mix pages?

![image](https://github.com/wavpoint/wavpoint-monorepo/assets/105757128/f10fc1b1-bac5-47ec-909c-acbe7aa91777)

**Comment by lootmatic** [comment]
Can use [sparkles](https://lucide.dev/icons/sparkles) as the mint count icon

**Comment by briceduke** [comment]
![image](https://github.com/wavpoint/wavpoint-monorepo/assets/74372754/40573443-cf3e-4137-9e63-6ca318d2f52c)
![image](https://github.com/wavpoint/wavpoint-monorepo/assets/74372754/d00546c5-b760-4a12-ad45-dae4f4435ec5)

Added, the icons are both small, but there is a sparkle and sparkles. Which do you think looks better, or should I change the size of the icon?

**Comment by lootmatic** [comment]
@briceduke let's do the second one
